### ISSUE TITLE
add feature: copy files recursively

### ISSUE THREAD

**Issue by Rhiath** [vsch/markdown-page-generator-plugin#2]
Due to the size of our documentation (and also to achieve a defined scope within a file), we have multiple pages. We want the image files of the pages to be placed in a separate subfolders to achieve separation of concerns. If possible we want the images to be placed in a folder next to the individual page, thus avoiding that all images of all pages are located in one folder.

For the actual pages, we are able to define "process all pages" using the "recursiveInput" configuration value; for copied files there does not seem to be an equivalent feature. Wildcards do not seem to be supported in the "copyDirectories" and we would like to avoid specifying every folder that contains our image resources.

We are looking towards having a folder structure like the one below, whilst only having to say "process all pages and copy all the image folders, whereever they are located in to markdown folder":
- Module 'A'
  - ModuleA.md
  - [FOLDER] images
- Module 'B'
  - ModuleB.md
  - [FOLDER] images
- mainDescription.md  (references ModuleA.md and ModuleB.md)
- [FOLDER] images

I think that supporting one of the following would be sufficient to enable what I am trying to achieve:
- add configuration value "copyResursively" (boolean) that is then mapped to the FileUtils call in MdPageGeneratorMojo::copyFiles line line 573 (third parameter in call)
- enrich "copyDirectories" configuration value to support wildcards such as: &lt;copyDirectories&gt;images,Module*/images&lt;/copyDirectories&gt;  or &lt;copyDirectories&gt;**/images&lt;/copyDirectories&gt;

**Comment by vsch** [comment]
@Rhiath, my knowledge of maven plugins is less than limited. I only replaced pegdown parser with flexmark-java library.

If you or anyone else is RWA to add this feature with corresponding tests I will merge it into the repo.

**Comment by Rhiath** [comment]
Hi, I will give it a try and provide you with a push notification when I think I am done.

**Comment by vsch** [comment]
Thank you.

**Comment by Rhiath** [comment]
I created a pull request. It builds locally, all added tests pass and the test coverage of new code should be sufficient.

I had to disable some build items temporarily (like GPG signing the JAR), I hope that I reverted all temporary changes correctly. Could you check if the resulting code works on your end?

**Comment by vsch** [comment]
@Rhiath, thank you. I will merge the changes and make a new release.

**Comment by vsch** [comment]
@Rhiath, PR merged. Repo updated. Maven released.

**Comment by Rhiath** [comment]
I tried out the new version today and it worked like a charm!
